package com.kuzhi.findme.common;

public enum PackEntityPresetField {
    CATEGORY,
    MOVEMENT,
    BINDING_REQUIREMENT,
    MOUNT_INTERACTION,
    BINDING_ANIMATION,
    RESCUE_MOTION,
    BOUNDS_SCALE,
    CIRCLE_SCALE,
    ARRIVAL_SOUND,
    ARRIVAL_VOLUME,
    ARRIVAL_PITCH,
    PREVIEW_NBT,
    RESET
}
